#
#   author: Tyranzx
#   us@stellarsquad
#
lang: en
#
redis:
  enabled: false
  host: 127.0.0.1
  port: 7777
  database: StellarCore
  username: root
  password: password
mysql: 
  host: 127.0.0.1
  port: 3306
  username: root
  password: "you_a_fool_123"
  ssl: false
