#
#   author: Tyranzx
#   us@stellarsquad
#
lang: en
#
redis:
  enabled: false
  host: 172.17.0.2
  port: 6379
mysql: 
  host: 127.0.0.1
  port: 3306
  username: root
  password: "@@you_a_fool_123"
  ssl: false
